Repository AY2324S2-CS2113-W13-4/tp, pull requests merged in 2024-04, with the labels that each got.

#74 Updated BookStorage to make code more readable
  src/main/java/bookmarked/storage/BookStorage.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.Medium

#58 Branch first ug draft
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#64 Branch dg help command
  docs/DeveloperGuide.md
  docs/diagrams/HelpCommandDiagram.puml
  docs/diagrams/WriteBookToTxtDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddCommandDiagram.png
  docs/images/HelpCommandDiagram.png
  docs/images/WriteBookToTxtDiagram.png
  docs/img.png
Labels: priority.High, type.Documentation

#55 Branch edit command
  book.txt
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/EditCommand.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, priority.Medium, type.Documentation

#78 Add listCommand by alphabetical and return date
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/ListCommand.java
  src/main/java/bookmarked/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#52 Branch j unit/parser
  book.txt
  src/main/java/bookmarked/parser/Parser.java
  src/test/java/bookmarked/Parser/ParserTest.java
  test.txt
Labels: priority.Medium, type.Test

#67 Branch j unit/delete command
  src/main/java/bookmarked/command/DeleteCommand.java
  src/test/java/bookmarked/command/DeleteCommandTest.java
Labels: priority.Medium, type.Test

#84 Updated UG
  docs/UserGuide.md
Labels: type.Documentation

#83 Add javadoc and junit for listCommand
  src/main/java/bookmarked/command/ListCommand.java
  src/test/java/bookmarked/command/ListCommandTest.java
Labels: type.Enhancement, priority.Medium, type.Documentation, type.Test

#80 Changed extend command to be more readable + added javadocs for Borro…
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/ExtendCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/main/java/bookmarked/exceptions/BookNotBorrowedException.java
  src/main/java/bookmarked/exceptions/BookNotFoundException.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
  src/test/java/bookmarked/BookTest.java
  src/test/java/bookmarked/command/BorrowCommandTest.java
  src/test/java/bookmarked/command/ExtendCommandTest.java
  src/test/java/bookmarked/command/ReturnCommandTest.java
Labels: type.Task, priority.Medium, type.Documentation

#86 Branch j unit/edit command
  src/main/java/bookmarked/command/EditCommand.java
  src/test/java/bookmarked/command/EditCommandTest.java
Labels: priority.Medium, type.Test

#56 addUser
  book.txt
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/BookMarked.java
  src/main/java/bookmarked/User.java
  src/main/java/bookmarked/command/AddCommand.java
  src/main/java/bookmarked/command/AddUserCommand.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/ListCommand.java
  src/main/java/bookmarked/command/ListUserCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
  src/test/java/bookmarked/Parser/ParserTest.java
  src/test/java/bookmarked/command/BorrowCommandTest.java
  test.txt
  testBooks.txt
Labels: type.Enhancement, priority.High

#93 add to summary page
  docs/UserGuide.md
Labels: type.Documentation

#95 update DG, UG, help list
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/bookmarked/ui/Ui.java
  src/test/java/bookmarked/command/BorrowCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, type.Documentation

#100 Branch edit accept title
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/EditCommand.java
  src/main/java/bookmarked/exceptions/NoEditChangeException.java
  src/main/java/bookmarked/ui/Ui.java
  src/test/java/bookmarked/command/EditCommandTest.java
Labels: type.Enhancement, priority.Medium

#134 Branch bug/help command
  src/main/java/bookmarked/exceptions/WrongInputFormatException.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.Low

#137 Branch bug/add user command
  src/main/java/bookmarked/command/BorrowCommand.java
Labels: type.Bug, severity.Low

#139 Updated BORROW and RETURN command to take in both name of book and in…
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/test/java/bookmarked/command/BorrowCommandTest.java
  src/test/java/bookmarked/command/ReturnCommandTest.java
Labels: type.Enhancement, type.Bug, priority.Medium

#97 Branch user storage
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/BookMarked.java
  src/main/java/bookmarked/User.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/storage/BookStorage.java
  src/main/java/bookmarked/storage/UserStorage.java
  src/test/java/bookmarked/Parser/ParserTest.java
  src/test/java/bookmarked/command/ReturnCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#141 Change list arguments for default
  src/main/java/bookmarked/command/ListCommand.java
  src/main/java/bookmarked/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#138 Branch bug/edit input command
  src/main/java/bookmarked/command/EditCommand.java
Labels: type.Bug, severity.Medium

#142 Updated return and storage to not accept invalid return dates
  src/main/java/bookmarked/storage/BookStorage.java
Labels: type.Bug, severity.Medium

#150 Update list user format
  src/main/java/bookmarked/command/ListCommand.java
  src/main/java/bookmarked/command/ListUserCommand.java
  src/main/java/bookmarked/exceptions/EmptyUserListException.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
  src/test/java/bookmarked/Parser/ParserTest.java
  src/test/java/bookmarked/command/ListCommandTest.java
Labels: type.Enhancement, priority.Medium

#151 add quantity
  docs/UserGuide.md
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/AddCommand.java
  src/main/java/bookmarked/exceptions/MaxIntNumberException.java
  src/main/java/bookmarked/exceptions/NegativeQuantityException.java
  src/main/java/bookmarked/exceptions/TooLargeQuantityException.java
  src/main/java/bookmarked/exceptions/WrongFormatQuantityException.java
  src/main/java/bookmarked/exceptions/WrongQuantityException.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
Labels: type.Epic, priority.High

#146 Branch bug/user storag store book index
  src/main/java/bookmarked/BookMarked.java
  src/main/java/bookmarked/User.java
  src/main/java/bookmarked/command/AddUserCommand.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/main/java/bookmarked/storage/UserStorage.java
  src/main/java/bookmarked/ui/Ui.java
Labels: type.Bug, severity.Medium

#155 Branch bug/user book storage different
  src/main/java/bookmarked/storage/BookStorage.java
  src/main/java/bookmarked/storage/UserStorage.java
  src/main/java/bookmarked/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.High

#157 Branch initial ppp
  docs/team/elyovs.md
  docs/team/johndoe.md
Labels: type.Task, priority.High, type.Documentation

#158 borrow quantity
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/BorrowCommand.java
Labels: type.Enhancement, priority.High

#159 Branch borrow user book availability
  src/main/java/bookmarked/command/BorrowCommand.java
Labels: type.Enhancement, priority.High

#162 update findby format
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/cayennegoh.md
  src/main/java/bookmarked/command/AddUserCommand.java
  src/main/java/bookmarked/command/FindCommand.java
  src/main/java/bookmarked/command/FindUserCommand.java
  src/main/java/bookmarked/command/ListUserCommand.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
Labels: type.Enhancement, priority.Medium

#167 Branch user borrow deadline
  build.gradle
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/BookMarked.java
  src/main/java/bookmarked/command/AddUserCommand.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/ExtendCommand.java
  src/main/java/bookmarked/command/FindCommand.java
  src/main/java/bookmarked/command/FindUserCommand.java
  src/main/java/bookmarked/command/ListCommand.java
  src/main/java/bookmarked/command/ListUserCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/main/java/bookmarked/exceptions/ReturnDateBeforeBorrowDateException.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/storage/UserStorage.java
  src/main/java/bookmarked/ui/Ui.java
  src/main/java/bookmarked/user/User.java
  src/main/java/bookmarked/userBook/UserBook.java
  src/test/java/bookmarked/Parser/ParserTest.java
  src/test/java/bookmarked/command/ListCommandTest.java
  src/test/java/bookmarked/command/ReturnCommandTest.java
Labels: type.Enhancement, priority.High

#172 updated borrow
  src/main/java/bookmarked/command/BorrowCommand.java
Labels: type.Task, priority.Medium

#173 Branch borrow return date extend
  src/main/java/bookmarked/command/AddUserCommand.java
  src/main/java/bookmarked/command/ExtendCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/main/java/bookmarked/storage/UserStorage.java
  src/main/java/bookmarked/ui/Ui.java
  src/main/java/bookmarked/user/User.java
Labels: type.Enhancement, priority.High

#176 Branch quantity storage
  src/main/java/bookmarked/command/EditCommand.java
  src/main/java/bookmarked/exceptions/DifferentUserBookStorageException.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/storage/BookStorage.java
  src/main/java/bookmarked/storage/UserStorage.java
  src/main/java/bookmarked/user/User.java
  src/main/java/bookmarked/userBook/UserBook.java
Labels: type.Enhancement, type.Bug, priority.High, severity.Medium

#179 OOP return and borrow, fixed bugs, changed some UI
  src/main/java/bookmarked/arguments/InputValidity.java
  src/main/java/bookmarked/arguments/SetBookIndexName.java
  src/main/java/bookmarked/arguments/SetUserName.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/DeleteCommand.java
  src/main/java/bookmarked/command/EditCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
Labels: type.Task, type.Bug, priority.High, severity.Medium

#182 Branch bug/user with no books not removed
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/main/java/bookmarked/storage/UserStorage.java
  src/main/java/bookmarked/ui/Ui.java
  src/main/java/bookmarked/user/User.java
Labels: type.Bug, severity.Low

#180 Sequence Diagrams for borrow,delete,extend,return
  docs/diagrams/BorrowCommandDiagram.puml
  docs/diagrams/DeleteCommandDiagram.puml
  docs/diagrams/ExtendCommandDiagram.puml
  docs/diagrams/ReturnCommandDiagram.puml
  src/main/java/bookmarked/command/ExtendCommand.java
  src/main/java/bookmarked/ui/Ui.java
Labels: priority.High, type.Documentation

#185 Branch bug/user storage cannot read borrow return date
  src/main/java/bookmarked/storage/UserStorage.java
  src/main/java/bookmarked/user/User.java
  src/main/java/bookmarked/userBook/UserBook.java
Labels: type.Bug, severity.High

#187 Branch bug/difference in book borrowed user book storage
  src/main/java/bookmarked/BookMarked.java
  src/main/java/bookmarked/arguments/StorageValidation.java
  src/main/java/bookmarked/storage/UserStorage.java
  src/main/java/bookmarked/ui/Ui.java
Labels: type.Bug, severity.Medium

#186 Updated BorrowCommandTest and ExtendCommandTest and ReturnCommandTest
  src/test/java/bookmarked/command/BorrowCommandTest.java
  src/test/java/bookmarked/command/ExtendCommandTest.java
  src/test/java/bookmarked/command/ReturnCommandTest.java
Labels: priority.Medium, type.Test

#191 Branch j unit/fix edit command
  src/test/java/bookmarked/BookTest.java
  src/test/java/bookmarked/Parser/ParserTest.java
  src/test/java/bookmarked/command/DeleteCommandTest.java
  src/test/java/bookmarked/command/EditCommandTest.java
  src/test/java/bookmarked/command/FindCommandTest.java
  src/test/java/bookmarked/command/ListUserCommandTest.java
Labels: type.Bug, severity.High, type.Test

#193 Branch ug/quick start
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#194 Branch ug/summary commands
  docs/UserGuide.md
  src/main/java/bookmarked/ui/Ui.java
Labels: priority.High, type.Documentation

#195 Branch ug/help command
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#210 Javadocs for AddCommand, BorrowCommand, DeleteCommand, EditCommand, E…
  src/main/java/bookmarked/command/AddCommand.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/DeleteCommand.java
  src/main/java/bookmarked/command/EditCommand.java
  src/main/java/bookmarked/command/ExtendCommand.java
  src/test/java/bookmarked/command/BorrowCommandTest.java
  src/test/java/bookmarked/command/ReturnCommandTest.java
Labels: priority.Low, type.Documentation

#209 add test
  docs/UserGuide.md
  src/main/java/bookmarked/command/FindUserCommand.java
  src/test/java/bookmarked/command/AddCommandTest.java
  src/test/java/bookmarked/command/FindUserCommandTest.java
  src/test/java/bookmarked/command/ListUserCommandTest.java
Labels: priority.Medium, type.Test

#215 Branch bug/storage unused print
  src/main/java/bookmarked/arguments/StorageValidation.java
  src/main/java/bookmarked/storage/BookStorage.java
  src/main/java/bookmarked/storage/UserStorage.java
Labels: type.Bug, severity.VeryLow

#222 Branch ug/edit command
  docs/UserGuide.md
  docs/images/code output/edit_example1.png
  docs/images/code output/edit_example2.png
  src/main/java/bookmarked/command/EditCommand.java
  src/main/java/bookmarked/exceptions/ExistedBookNameException.java
  src/main/java/bookmarked/exceptions/InvalidBookException.java
  src/main/java/bookmarked/exceptions/SameBookNameException.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/storage/BookStorage.java
  src/main/java/bookmarked/ui/Ui.java
Labels: type.Bug, priority.High, severity.Medium, type.Documentation

#224 Branch j unit/fix
  book.txt
  src/main/java/bookmarked/command/FindCommand.java
  src/main/java/bookmarked/storage/BookStorage.java
  src/test/java/bookmarked/BookTest.java
  src/test/java/bookmarked/command/AddCommandTest.java
  src/test/java/bookmarked/command/BorrowCommandTest.java
  src/test/java/bookmarked/command/DeleteCommandTest.java
  src/test/java/bookmarked/command/EditCommandTest.java
  src/test/java/bookmarked/command/ExtendCommandTest.java
  src/test/java/bookmarked/command/FindCommandTest.java
  src/test/java/bookmarked/command/FindUserCommandTest.java
  src/test/java/bookmarked/command/ListUserCommandTest.java
  src/test/java/bookmarked/command/ReturnCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  user.txt
Labels: type.Task, priority.High, type.Test

#226 Branch ug/storage
  docs/UserGuide.md
  docs/images/code output/bye_example.png
  src/main/java/bookmarked/ui/Ui.java
  src/test/java/bookmarked/command/DeleteCommandTest.java
  src/test/java/bookmarked/command/ReturnCommandTest.java
Labels: priority.High, type.Documentation

#246 Update list UG
  docs/UserGuide.md
  docs/diagrams/AddCommand.puml
  docs/diagrams/style.puml
  docs/team/elyovs.md
  src/main/java/bookmarked/command/ListUserCommand.java
  src/main/java/bookmarked/command/PrintUserBooksCommand.java
  src/test/java/bookmarked/command/AddCommandTest.java
  src/test/java/bookmarked/command/FindUserCommandTest.java
Labels: severity.Low, severity.Medium

#248 Branch dg/storage
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ReadFileStorageDiagram.puml
  docs/diagrams/ReadFileStorageUserDiagram.puml
  docs/diagrams/ValidateUserBooksListsDiagram.puml
  docs/diagrams/WriteBookToTxtDiagram.puml
  docs/diagrams/WriteUserToTxtDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ReadFileStorageDiagram.png
  docs/images/ReadFileStorageUserDiagram.png
  docs/images/ValidateUserBooksListsDiagram.png
  docs/images/WriteBookToTxtDiagram.png
  docs/images/WriteUserToTxtDiagram.png
Labels: priority.High, type.Documentation

#249 fix gradle, update DG Edit
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/CommandComponentClassDiagram.puml
  docs/diagrams/EditCommandDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/EditCommandDiagram.png
  docs/images/code output/bye_example.png
  src/main/java/bookmarked/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Documentation

#256 Branch dg/user component
  docs/DeveloperGuide.md
  docs/diagrams/CommandComponentClassDiagram.puml
  docs/diagrams/UserComponentClassDiagram.puml
  docs/images/CommandComponentClassDiagram.png
  docs/images/UserComponentClassDiagram.png
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/user/User.java
  src/main/java/bookmarked/userBook/UserBook.java
Labels: type.Bug, priority.High, type.Documentation

#253 DG - addcommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommand.puml
  docs/diagrams/ExitClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddCommandDiagram.png
  src/main/java/bookmarked/command/FindUserCommand.java
  src/main/java/bookmarked/command/PrintUserBooksCommand.java
  src/main/java/bookmarked/ui/Ui.java
  src/test/java/bookmarked/command/FindUserCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, severity.Low

#257 add non-functional requirements
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#261 Branch dg/user book component
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/UserComponentClassDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/UserComponentClassDiagram.png
  src/main/java/bookmarked/userBook/UserBook.java
Labels: priority.High, type.Documentation

#262 Branch dg/fix diagram
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandDiagram.puml
  docs/images/EditCommandDiagram.png
  src/main/java/bookmarked/command/ExitCommand.java
  src/main/java/bookmarked/command/ExtendCommand.java
  src/main/java/bookmarked/command/FindCommand.java
  src/main/java/bookmarked/command/HelpCommand.java
  src/main/java/bookmarked/command/ListCommand.java
  src/main/java/bookmarked/command/ListUserCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
Labels: priority.High, type.Documentation

#263 update diagram, ui component
  docs/DeveloperGuide.md
  docs/diagrams/UiComponentClassDiagram.puml
  docs/images/AddCommand.png
  docs/images/ExitClassDiagram.png
  docs/images/UiComponentClassDiagram.png
  src/main/java/bookmarked/ui/Ui.java
Labels: priority.Medium

#265 Branch dg/manual testing instruction
  docs/DeveloperGuide.md
  docs/diagrams/UserComponentClassDiagram.puml
  docs/images/UserComponentClassDiagram.png
Labels: priority.High, type.Documentation

#270 Branch update ppp
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ParserClassDiagram.puml
  docs/images/ParserClassDiagram.png
  docs/team/elyovs.md
  src/main/java/bookmarked/parser/Parser.java
Labels: priority.High, type.Documentation

#274 Parser class diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddCommand.puml
  docs/diagrams/ParserComponentClassDiagram.puml
  docs/images/AddCommand.png
  docs/images/ParserComponentClassDiagram.png
Labels: priority.Medium

#279 Add Parser Sequence diagram
  docs/diagrams/EditCommandDiagram.puml
  docs/diagrams/ParserSequenceDiagram.puml
  docs/images/ParserClassDiagram.png
  docs/images/ParserSequenceDiagram.png
Labels: priority.High, type.Documentation

#284 parser DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#285 fix return
  docs/diagrams/WriteBookToTxtDiagram.puml
  docs/diagrams/WriteUserToTxtDiagram.puml
  docs/images/WriteBookToTxtDiagram.png
  docs/images/WriteUserToTxtDiagram.png
Labels: type.Bug, type.Documentation

#288 Branch dg/fix user read
  docs/diagrams/ReadFileStorageUserDiagram.puml
  docs/images/ReadFileStorageUserDiagram.png
Labels: type.Bug, type.Documentation
