Repository AY2324S2-CS2113-W13-4/tp, pull requests merged in 2024-03, with the labels that each got.

#23 Updated borrow and return commands to take in name of book as an input.
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
Labels: priority.High

#24 Branch find command
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/FindCommand.java
  src/main/java/bookmarked/parser/Parser.java
Labels: type.Task, priority.High

#33 Branch book storage
  book.txt
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/BookMarked.java
  src/main/java/bookmarked/command/AddCommand.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/command/DeleteCommand.java
  src/main/java/bookmarked/command/FindCommand.java
  src/main/java/bookmarked/command/ReturnCommand.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/storage/BookStorage.java
  src/test/java/bookmarked/BookTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.Medium

#42 Branch lists
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/ListCommand.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.Medium

#43 Branch bug/storage print
  src/main/java/bookmarked/storage/BookStorage.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.Medium

#45 Branch first dg draft
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ReadFileStorageDiagram.puml
  docs/diagrams/WriteBookToTxt.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ReadFileStorageDiagram.png
  docs/images/WriteBookToTxt.png
  src/main/java/bookmarked/command/ListCommand.java
Labels: type.Task, priority.Medium

#46 BorrowCommand DG update
  docs/DeveloperGuide.md
Labels: priority.Medium

#51 Updates to BorrowCommand (expected return date, availability)
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/BorrowCommand.java
  src/main/java/bookmarked/storage/BookStorage.java
  src/test/java/bookmarked/BookTest.java
Labels: priority.High

#50 Branch bug/delete index out of bound
  src/main/java/bookmarked/command/DeleteCommand.java
Labels: type.Bug, severity.Medium

#44 Branch j unit find command
  book.txt
  src/main/java/bookmarked/command/FindCommand.java
  src/test/java/bookmarked/command/FindCommandTest.java
Labels: priority.Medium, type.Test

#57 Added ExtendCommand Class
  src/main/java/bookmarked/Book.java
  src/main/java/bookmarked/command/ExtendCommand.java
  src/main/java/bookmarked/parser/Parser.java
  src/main/java/bookmarked/ui/Ui.java
  src/test/java/bookmarked/BookTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#66 Branch fix storage
  book.txt
  src/main/java/bookmarked/storage/BookStorage.java
Labels: type.Bug, severity.VeryLow

#70 Branch dg/fix footbox
  docs/diagrams/ReadFileStorageDiagram.puml
  docs/diagrams/WriteBookToTxt.puml
Labels: type.Bug, severity.VeryLow, type.Documentation
